"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from pathlib import Path
from setuptools import setup
import constants

import google.protobuf

# This is a dumb workaround because otherwise the protobuf library can't be loaded as a
# package by py2app. See https://github.com/ronaldoussoren/py2app/issues/495
google_folder = Path(google.protobuf.__file__).parent.parent
Path.touch(google_folder / "__init__.py")
Path.touch(google_folder / "_upb" / "__init__.py")

APP = ["main.py"]
DATA_FILES = []
OPTIONS = {
    "iconfile": "resources/rprdigi.icns",
    "resources": [
        "resources/icons",
        "resources/markermaticicon.ico",
        "resources/MarkerMatic-Bridge.bwextension",
    ],
    "includes": ["mido.backends.portmidi"],
    "excludes": ["pyinstaller", "pyinstaller-hooks-contrib"],
    "dylib_excludes": [
        "/Library/Frameworks/Python.framework/Versions/3.13/Frameworks/Tcl.framework",
        "/Library/Frameworks/Python.framework/Versions/3.13/Frameworks/Tk.framework",
    ],
    "plist": {
        "CFBundleIdentifier": constants.BUNDLE_IDENTIFIER,
        "CFBundleName": constants.APPLICATION_NAME,
        "CFBundleDisplayName": constants.APPLICATION_NAME,
        "NSHumanReadableCopyright": constants.APPLICATION_COPYRIGHT,
        "CFBundleShortVersionString": constants.VERSION,
        "CFBundleVersion": constants.VERSION,
        "NSRequiresAquaSystemAppearance": False,
    },
    "packages": ["google.protobuf", "google._upb"],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
