"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import platform
import sys
from pathlib import Path

import google.protobuf
from setuptools import setup

import constants

# This is a dumb workaround because otherwise the protobuf library can't be loaded as a
# package by py2app. See https://github.com/ronaldoussoren/py2app/issues/495
google_folder = Path(google.protobuf.__file__).parent.parent
Path.touch(google_folder / "__init__.py")
Path.touch(google_folder / "_upb" / "__init__.py")

APP = ["main.py"]
DATA_FILES = []

su_feed_url = constants.SPARKLE_MAC_X64_URL
if platform.machine() == "arm64":
    su_feed_url = constants.SPARKLE_MAC_ARM64_URL

OPTIONS = {
    "argv_emulation": False,
    "iconfile": f"resources/{constants.ICON_MAC_FILENAME}",
    "resources": [
        "resources/icons",
        f"resources/{constants.ICON_WIN_FILENAME}",
        "resources/MarkerMatic-Bridge.bwextension",
    ],
    "excludes": ["pyinstaller", "pyinstaller-hooks-contrib", "setuptools"],
    "frameworks": ["resources/Sparkle/Sparkle.framework"],
    "dylib_excludes": [
        f"/Library/Frameworks/Python.framework/Versions/{sys.version_info.major}.{sys.version_info.minor}/Frameworks/Tcl.framework",
        f"/Library/Frameworks/Python.framework/Versions/{sys.version_info.major}.{sys.version_info.minor}/Frameworks/Tk.framework",
    ],
    "plist": {
        "CFBundleIdentifier": constants.BUNDLE_IDENTIFIER,
        "CFBundleName": constants.APPLICATION_NAME,
        "CFBundleDisplayName": constants.APPLICATION_NAME,
        "NSHumanReadableCopyright": constants.APPLICATION_COPYRIGHT,
        "CFBundleShortVersionString": constants.VERSION_SHORT,
        "CFBundleVersion": constants.VERSION_EXTRA,
        "NSRequiresAquaSystemAppearance": False,
        "NSDocumentsFolderUsageDescription": f"{constants.APPLICATION_NAME} needs to install a Bitwig Studio extension to connect",
        "NSLocalNetworkUsageDescription": f"{constants.APPLICATION_NAME} communicates with your console to detect cue loads",
        "NSAutoFillRequiresTextContentTypeForOneTimeCodeOnMac": True,
        "SUFeedURL": su_feed_url,
        "SUPublicEDKey": constants.SPARKLE_PUBLIC_ED_KEY,
    },
    "packages": ["google.protobuf", "google._upb", "zeroconf"],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
