"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from pathlib import Path
from setuptools import setup
import constants
import sys
import google.protobuf

# This is a dumb workaround because otherwise the protobuf library can't be loaded as a
# package by py2app. See https://github.com/ronaldoussoren/py2app/issues/495
google_folder = Path(google.protobuf.__file__).parent.parent
Path.touch(google_folder / "__init__.py")
Path.touch(google_folder / "_upb" / "__init__.py")

APP = ["main.py"]
DATA_FILES = []
OPTIONS = {
    "argv_emulation": False,
    "iconfile": f"resources/{constants.ICON_MAC_FILENAME}",
    "resources": [
        "resources/icons",
        f"resources/{constants.ICON_WIN_FILENAME}",
        "resources/MarkerMatic-Bridge.bwextension",
    ],
    "excludes": ["pyinstaller", "pyinstaller-hooks-contrib"],
    "dylib_excludes": [
        f"/Library/Frameworks/Python.framework/Versions/{sys.version_info.major}.{sys.version_info.minor}/Frameworks/Tcl.framework",
        f"/Library/Frameworks/Python.framework/Versions/{sys.version_info.major}.{sys.version_info.minor}/Frameworks/Tk.framework",
    ],
    "plist": {
        "CFBundleIdentifier": constants.BUNDLE_IDENTIFIER,
        "CFBundleName": constants.APPLICATION_NAME,
        "CFBundleDisplayName": constants.APPLICATION_NAME,
        "NSHumanReadableCopyright": constants.APPLICATION_COPYRIGHT,
        "CFBundleShortVersionString": constants.VERSION,
        "CFBundleVersion": constants.VERSION,
        "NSRequiresAquaSystemAppearance": False,
        "NSDocumentsFolderUsageDescription": f"{constants.APPLICATION_NAME} needs to install a Bitwig Studio extension to connect",
        "NSLocalNetworkUsageDescription": f"{constants.APPLICATION_NAME} communicates with your console to detect cue loads",
    },
    "packages": ["google.protobuf", "google._upb"],
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={"py2app": OPTIONS},
    setup_requires=["py2app"],
)
