name: Post-release publishing
on:
  release:
  workflow_dispatch:
jobs:
  trigger_website_build:
    name: Trigger website build
    runs-on: ubuntu-slim
    steps:
      - name: Trigger website build
        run: 'curl --silent --output /dev/null --show-error --fail --json ''{"branch":"main"}'' -X POST -H "Authorization: Bearer ${{ secrets.trigger_ci_build_token }}" "${{ secrets.trigger_ci_site_build_url }}"'
